/* ==========================================================================
   六十四卦完整数据（去重补全版）
   ========================================================================== */

// 卦象数据接口
export interface HexagramData {
  id: number;
  name: string;
  symbol: string; // 八卦符号组合，如 "☰☰"
  binarySymbol: string; // 六位二进制字符串，1 为阳爻，0 为阴爻
  upper: string; // 上卦
  lower: string; // 下卦
  palace: string; // 所属八宫
  description: string;
  yaoCi?: string[]; // 爻辞（初爻到上爻）
}

// 八卦基础数据接口
export interface TrigramData {
  name: string;
  symbol: string; // 八卦符号
  nature: string; // 自然属性
  element: string; // 五行属性
  lines: number[]; // 爻线数组，1 为阳爻，0 为阴爻
}

// 八卦数据（字符串键格式，用于二进制查找）
const trigramsByBinary: Record<string, TrigramData> = {
  '111': { name: '乾', symbol: '☰', nature: '天', element: '金', lines: [1, 1, 1] },
  '110': { name: '兑', symbol: '☱', nature: '泽', element: '金', lines: [1, 1, 0] },
  '101': { name: '离', symbol: '☲', nature: '火', element: '火', lines: [1, 0, 1] },
  '001': { name: '震', symbol: '☳', nature: '雷', element: '木', lines: [0, 0, 1] },
  '011': { name: '巽', symbol: '☴', nature: '风', element: '木', lines: [0, 1, 1] },
  '010': { name: '坎', symbol: '☵', nature: '水', element: '水', lines: [0, 1, 0] },
  '100': { name: '艮', symbol: '☶', nature: '山', element: '土', lines: [1, 0, 0] },
  '000': { name: '坤', symbol: '☷', nature: '地', element: '土', lines: [0, 0, 0] },
};

// 八卦数据（数字键格式，用于索引查找）
export const trigramsByIndex: Record<number, TrigramData> = {
  1: trigramsByBinary['111'], // 乾
  2: trigramsByBinary['110'], // 兑
  3: trigramsByBinary['101'], // 离
  4: trigramsByBinary['001'], // 震
  5: trigramsByBinary['011'], // 巽
  6: trigramsByBinary['010'], // 坎
  7: trigramsByBinary['100'], // 艮
  8: trigramsByBinary['000'], // 坤
};

// 六十四卦完整数据（按传统八宫卦序排列）
const rawHexagramsData = [
  /* 乾宫 */
  {
    id: 1,
    name: '乾为天',
    symbol: '☰☰',
    binarySymbol: '111111',
    upper: '乾',
    lower: '乾',
    palace: '乾',
    description: '元亨利贞',
    yaoCi: [
      '潜龙勿用',
      '见龙在田，利见大人',
      '君子终日乾乾，夕惕若厉，无咎',
      '或跃在渊，无咎',
      '飞龙在天，利见大人',
      '亢龙有悔',
    ],
  },
  {
    id: 44,
    name: '天风姤',
    symbol: '☰☴',
    binarySymbol: '111011',
    upper: '乾',
    lower: '巽',
    palace: '乾',
    description: '女壮，勿用取女',
  },
  {
    id: 33,
    name: '天山遁',
    symbol: '☰☶',
    binarySymbol: '111100',
    upper: '乾',
    lower: '艮',
    palace: '乾',
    description: '亨，小利贞',
  },
  {
    id: 12,
    name: '天地否',
    symbol: '☰☷',
    binarySymbol: '111000',
    upper: '乾',
    lower: '坤',
    palace: '乾',
    description: '否之匪人，不利君子贞',
    yaoCi: [
      '拔茅茹以其汇，贞吉亨',
      '包承，小人吉，大人否亨',
      '包羞',
      '有命无咎，畴离祉',
      '休否，大人吉',
      '倾否，先否后喜',
    ],
  },
  {
    id: 20,
    name: '风地观',
    symbol: '☴☷',
    binarySymbol: '011000',
    upper: '巽',
    lower: '坤',
    palace: '乾',
    description: '盥而不荐，有孚颙若',
    yaoCi: [
      '童观，小人无咎',
      '窥观，利女贞',
      '观我生，进退',
      '观国之光，利用宾于王',
      '观我生，君子无咎',
      '观其生，君子无咎',
    ],
  },
  {
    id: 23,
    name: '山地剥',
    symbol: '☶☷',
    binarySymbol: '100000',
    upper: '艮',
    lower: '坤',
    palace: '乾',
    description: '不利有攸往',
  },
  {
    id: 35,
    name: '火地晋',
    symbol: '☲☷',
    binarySymbol: '101000',
    upper: '离',
    lower: '坤',
    palace: '乾',
    description: '康侯用锡马蕃庶',
  },
  {
    id: 14,
    name: '火天大有',
    symbol: '☲☰',
    binarySymbol: '101111',
    upper: '离',
    lower: '乾',
    palace: '乾',
    description: '元亨',
    yaoCi: [
      '无交害，匪咎，艰则无咎',
      '大车以载，有攸往，无咎',
      '公用亨于天子',
      '匪其彭，无咎',
      '厥孚交如威如，吉',
      '自天祐之，吉无不利',
    ],
  },

  /* 坎宫 */
  {
    id: 29,
    name: '坎为水',
    symbol: '☵☵',
    binarySymbol: '010010',
    upper: '坎',
    lower: '坎',
    palace: '坎',
    description: '习坎，有孚，维心亨',
    yaoCi: [
      '习坎，入于坎窞，凶',
      '坎有险，求小得',
      '来之坎坎，险且枕，入于坎窞，勿用',
      '樽酒簋贰，用缶，纳约自牖，终无咎',
      '坎不盈，祗既平，无咎',
      '系用徽纆，寘于丛棘，三岁不得，凶',
    ],
  },
  {
    id: 60,
    name: '水泽节',
    symbol: '☵☱',
    binarySymbol: '010110',
    upper: '坎',
    lower: '兑',
    palace: '坎',
    description: '亨，苦节不可贞',
  },
  {
    id: 3,
    name: '水雷屯',
    symbol: '☵☳',
    binarySymbol: '010001',
    upper: '坎',
    lower: '震',
    palace: '坎',
    description: '元亨利贞，勿用有攸往',
  },
  {
    id: 63,
    name: '水火既济',
    symbol: '☵☲',
    binarySymbol: '010101',
    upper: '坎',
    lower: '离',
    palace: '坎',
    description: '亨小，利贞',
    yaoCi: [
      '曳其轮，濡其尾，无咎',
      '妇丧其茀，勿逐，七日得',
      '高宗伐鬼方，三年克之',
      '繻有衣袽，终日戒',
      '东邻杀牛，不如西邻之禴祭，实受其福',
      '濡其首，厉',
    ],
  },
  {
    id: 49,
    name: '泽火革',
    symbol: '☱☲',
    binarySymbol: '110101',
    upper: '兑',
    lower: '离',
    palace: '坎',
    description: '己日乃孚，元亨利贞',
  },
  {
    id: 55,
    name: '雷火丰',
    symbol: '☳☲',
    binarySymbol: '001101',
    upper: '震',
    lower: '离',
    palace: '坎',
    description: '亨，王假之',
  },
  {
    id: 36,
    name: '地火明夷',
    symbol: '☷☲',
    binarySymbol: '000101',
    upper: '坤',
    lower: '离',
    palace: '坎',
    description: '利艰贞',
  },
  {
    id: 7,
    name: '地水师',
    symbol: '☷☵',
    binarySymbol: '000010',
    upper: '坤',
    lower: '坎',
    palace: '坎',
    description: '贞，丈人吉，无咎',
    yaoCi: [
      '师出以律，否臧凶',
      '在师中吉，无咎',
      '师或舆尸，凶',
      '师左次，无咎',
      '田有禽，利执言',
      '大君有命，开国承家',
    ],
  },

  /* 艮宫 */
  {
    id: 52,
    name: '艮为山',
    symbol: '☶☶',
    binarySymbol: '100100',
    upper: '艮',
    lower: '艮',
    palace: '艮',
    description: '艮其背，不获其身',
    yaoCi: [
      '艮其趾，无咎，利永贞',
      '艮其腓，不拯其随，其心不快',
      '艮其限，列其夤，厉薰心',
      '艮其身，无咎',
      '艮其辅，言有序，悔亡',
      '敦艮，吉',
    ],
  },
  {
    id: 22,
    name: '山火贲',
    symbol: '☶☲',
    binarySymbol: '100101',
    upper: '艮',
    lower: '离',
    palace: '艮',
    description: '亨，小利有攸往',
  },
  {
    id: 26,
    name: '山天大畜',
    symbol: '☶☰',
    binarySymbol: '100111',
    upper: '艮',
    lower: '乾',
    palace: '艮',
    description: '利贞，不家食吉',
  },
  {
    id: 41,
    name: '山泽损',
    symbol: '☶☱',
    binarySymbol: '100110',
    upper: '艮',
    lower: '兑',
    palace: '艮',
    description: '有孚，元吉，无咎',
  },
  {
    id: 38,
    name: '火泽睽',
    symbol: '☲☱',
    binarySymbol: '101110',
    upper: '离',
    lower: '兑',
    palace: '艮',
    description: '小事吉',
  },
  {
    id: 10,
    name: '天泽履',
    symbol: '☰☱',
    binarySymbol: '111110',
    upper: '乾',
    lower: '兑',
    palace: '艮',
    description: '履虎尾，不咥人，亨',
    yaoCi: [
      '素履，往无咎',
      '履道坦坦，幽人贞吉',
      '眇能视，跛能履',
      '履虎尾，愬愬终吉',
      '夬履，贞厉',
      '视履考祥，其旋元吉',
    ],
  },
  {
    id: 61,
    name: '风泽中孚',
    symbol: '☴☱',
    binarySymbol: '011110',
    upper: '巽',
    lower: '兑',
    palace: '艮',
    description: '豚鱼吉，利涉大川',
  },
  {
    id: 53,
    name: '风山渐',
    symbol: '☴☶',
    binarySymbol: '011100',
    upper: '巽',
    lower: '艮',
    palace: '艮',
    description: '女归吉，利贞',
  },

  /* 震宫 */
  {
    id: 51,
    name: '震为雷',
    symbol: '☳☳',
    binarySymbol: '001001',
    upper: '震',
    lower: '震',
    palace: '震',
    description: '亨，震来虩虩',
    yaoCi: [
      '震来虩虩，后笑言哑哑，吉',
      '震来厉，亿丧贝，跻于九陵，勿逐，七日得',
      '震苏苏，震行无眚',
      '震遂泥',
      '震往来厉，亿无丧，有事',
      '震索索，视矍矍，征凶',
    ],
  },
  {
    id: 16,
    name: '雷地豫',
    symbol: '☳☷',
    binarySymbol: '001000',
    upper: '震',
    lower: '坤',
    palace: '震',
    description: '利建侯行师',
    yaoCi: [
      '鸣豫，凶',
      '介于石，不终日，贞吉',
      '盱豫，悔，迟有悔',
      '由豫，大有得',
      '贞疾，恒不死',
      '冥豫，成有渝',
    ],
  },
  {
    id: 40,
    name: '雷水解',
    symbol: '☳☵',
    binarySymbol: '001010',
    upper: '震',
    lower: '坎',
    palace: '震',
    description: '利西南，无所往',
  },
  {
    id: 32,
    name: '雷风恒',
    symbol: '☳☴',
    binarySymbol: '001011',
    upper: '震',
    lower: '巽',
    palace: '震',
    description: '亨，无咎，利贞',
  },
  {
    id: 46,
    name: '地风升',
    symbol: '☷☴',
    binarySymbol: '000011',
    upper: '坤',
    lower: '巽',
    palace: '震',
    description: '元亨，用见大人，勿恤',
  },
  {
    id: 48,
    name: '水风井',
    symbol: '☵☴',
    binarySymbol: '010011',
    upper: '坎',
    lower: '巽',
    palace: '震',
    description: '改邑不改井',
  },
  {
    id: 28,
    name: '泽风大过',
    symbol: '☱☴',
    binarySymbol: '110011',
    upper: '兑',
    lower: '巽',
    palace: '震',
    description: '栋桡，利有攸往',
  },
  {
    id: 17,
    name: '泽雷随',
    symbol: '☱☳',
    binarySymbol: '110001',
    upper: '兑',
    lower: '震',
    palace: '震',
    description: '元亨利贞，无咎',
    yaoCi: [
      '官有渝，贞吉',
      '系小子，失丈夫',
      '系丈夫，失小子',
      '随有获，贞凶',
      '孚于嘉，吉',
      '拘系之，乃从维之',
    ],
  },

  /* 巽宫 */
  {
    id: 57,
    name: '巽为风',
    symbol: '☴☴',
    binarySymbol: '011011',
    upper: '巽',
    lower: '巽',
    palace: '巽',
    description: '小亨，利有攸往',
    yaoCi: [
      '进退，利武人之贞',
      '巽在床下，用史巫纷若，吉，无咎',
      '频巽，吝',
      '悔亡，田获三品',
      '贞吉悔亡，无不利，无初有终',
      '巽在床下，丧其资斧，贞凶',
    ],
  },
  {
    id: 9,
    name: '风天小畜',
    symbol: '☴☰',
    binarySymbol: '011111',
    upper: '巽',
    lower: '乾',
    palace: '巽',
    description: '亨，密云不雨',
    yaoCi: [
      '复自道，何其咎，吉',
      '牵复，吉',
      '舆说辐，夫妻反目',
      '有孚，血去惕出，无咎',
      '有孚挛如，富以其邻',
      '既雨既处，尚德载',
    ],
  },
  {
    id: 37,
    name: '风火家人',
    symbol: '☴☲',
    binarySymbol: '011101',
    upper: '巽',
    lower: '离',
    palace: '巽',
    description: '利女贞',
  },
  {
    id: 42,
    name: '风雷益',
    symbol: '☴☳',
    binarySymbol: '011001',
    upper: '巽',
    lower: '震',
    palace: '巽',
    description: '利有攸往，利涉大川',
  },
  {
    id: 25,
    name: '天雷无妄',
    symbol: '☰☳',
    binarySymbol: '111001',
    upper: '乾',
    lower: '震',
    palace: '巽',
    description: '元亨利贞',
  },
  {
    id: 21,
    name: '火雷噬嗑',
    symbol: '☲☳',
    binarySymbol: '101001',
    upper: '离',
    lower: '震',
    palace: '巽',
    description: '亨，利用狱',
  },
  {
    id: 27,
    name: '山雷颐',
    symbol: '☶☳',
    binarySymbol: '100001',
    upper: '艮',
    lower: '震',
    palace: '巽',
    description: '贞吉，观颐',
  },
  {
    id: 18,
    name: '山风蛊',
    symbol: '☶☴',
    binarySymbol: '100011',
    upper: '艮',
    lower: '巽',
    palace: '巽',
    description: '元亨，利涉大川',
    yaoCi: [
      '干父之蛊，有子',
      '干母之蛊，不可贞',
      '干父之蛊，小有悔',
      '裕父之蛊，往见吝',
      '干父之蛊，用誉',
      '不事王侯，高尚其事',
    ],
  },

  /* 离宫 */
  {
    id: 30,
    name: '离为火',
    symbol: '☲☲',
    binarySymbol: '101101',
    upper: '离',
    lower: '离',
    palace: '离',
    description: '利贞，亨，畜牝牛吉',
    yaoCi: [
      '履错然，敬之无咎',
      '黄离，元吉',
      '日昃之离，不鼓缶而歌，则大耋之嗟，凶',
      '突如其来如，焚如，死如，弃如',
      '出涕沱若，戚嗟若，吉',
      '王用出征，有嘉折首，获匪其丑，无咎',
    ],
  },
  {
    id: 56,
    name: '火山旅',
    symbol: '☲☶',
    binarySymbol: '101100',
    upper: '离',
    lower: '艮',
    palace: '离',
    description: '小亨，旅贞吉',
  },
  {
    id: 50,
    name: '火风鼎',
    symbol: '☲☴',
    binarySymbol: '101011',
    upper: '离',
    lower: '巽',
    palace: '离',
    description: '元吉，亨',
  },
  {
    id: 64,
    name: '火水未济',
    symbol: '☲☵',
    binarySymbol: '101010',
    upper: '离',
    lower: '坎',
    palace: '离',
    description: '亨，小狐汔济，濡其尾',
    yaoCi: [
      '濡其尾，吝',
      '曳其轮，贞吉',
      '未济，征凶，利涉大川',
      '贞吉，悔亡，震用伐鬼方，三年有赏于大国',
      '贞吉，无悔，君子之光，有孚吉',
      '有孚于饮酒，无咎，濡其首，有孚失是',
    ],
  },
  {
    id: 4,
    name: '山水蒙',
    symbol: '☶☵',
    binarySymbol: '100010',
    upper: '艮',
    lower: '坎',
    palace: '离',
    description: '亨，匪我求童蒙',
    yaoCi: [
      '发蒙，利用刑人',
      '包蒙吉，纳妇吉',
      '勿用取女，见金夫',
      '困蒙，吝',
      '童蒙，吉',
      '击蒙，不利为寇',
    ],
  },
  {
    id: 59,
    name: '风水涣',
    symbol: '☴☵',
    binarySymbol: '011010',
    upper: '巽',
    lower: '坎',
    palace: '离',
    description: '亨，王假有庙',
  },
  {
    id: 6,
    name: '天水讼',
    symbol: '☰☵',
    binarySymbol: '111010',
    upper: '乾',
    lower: '坎',
    palace: '离',
    description: '有孚，窒惕，中吉',
    yaoCi: [
      '不永所事，小有言，终吉',
      '不克讼，归而逋',
      '食旧德，贞厉，终吉',
      '不克讼，复即命渝',
      '讼，元吉',
      '或锡之鞶带，终朝三褫之',
    ],
  },
  {
    id: 13,
    name: '天火同人',
    symbol: '☰☲',
    binarySymbol: '111101',
    upper: '乾',
    lower: '离',
    palace: '离',
    description: '同人于野，亨',
    yaoCi: [
      '同人于门，无咎',
      '同人于宗，吝',
      '伏戎于莽，升其高陵',
      '乘其墉，弗克攻，吉',
      '同人先号咷而后笑',
      '同人于郊，无悔',
    ],
  },

  /* 坤宫 */
  {
    id: 2,
    name: '坤为地',
    symbol: '☷☷',
    binarySymbol: '000000',
    upper: '坤',
    lower: '坤',
    palace: '坤',
    description: '元亨，利牝马之贞',
    yaoCi: [
      '履霜，坚冰至',
      '直方大，不习无不利',
      '含章可贞，或从王事，无成有终',
      '括囊，无咎无誉',
      '黄裳，元吉',
      '龙战于野，其血玄黄',
    ],
  },
  {
    id: 24,
    name: '地雷复',
    symbol: '☷☳',
    binarySymbol: '000001',
    upper: '坤',
    lower: '震',
    palace: '坤',
    description: '亨，出入无疾',
  },
  {
    id: 19,
    name: '地泽临',
    symbol: '☷☱',
    binarySymbol: '000110',
    upper: '坤',
    lower: '兑',
    palace: '坤',
    description: '元亨利贞，至于八月有凶',
    yaoCi: [
      '咸临，贞吉',
      '咸临，吉，无不利',
      '甘临，无攸利',
      '至临，无咎',
      '知临，大君之宜，吉',
      '敦临，吉，无咎',
    ],
  },
  {
    id: 11,
    name: '地天泰',
    symbol: '☷☰',
    binarySymbol: '000111',
    upper: '坤',
    lower: '乾',
    palace: '坤',
    description: '小往大来，吉亨',
    yaoCi: [
      '拔茅茹以其汇，征吉',
      '包荒，用冯河，不遐遗，朋亡，得尚于中行',
      '无平不陂，无往不复，艰贞无咎',
      '翩翩，不富以其邻，不戒以孚',
      '帝乙归妹，以祉元吉',
      '城复于隍，勿用师',
    ],
  },
  {
    id: 34,
    name: '雷天大壮',
    symbol: '☳☰',
    binarySymbol: '001111',
    upper: '震',
    lower: '乾',
    palace: '坤',
    description: '利贞',
  },
  {
    id: 43,
    name: '泽天夬',
    symbol: '☱☰',
    binarySymbol: '110111',
    upper: '兑',
    lower: '乾',
    palace: '坤',
    description: '扬于王庭，孚号有厉',
  },
  {
    id: 5,
    name: '水天需',
    symbol: '☵☰',
    binarySymbol: '010111',
    upper: '坎',
    lower: '乾',
    palace: '坤',
    description: '有孚，光亨，贞吉',
    yaoCi: [
      '需于郊，利用恒，无咎',
      '需于沙，小有言，终吉',
      '需于泥，致寇至',
      '需于血，出自穴',
      '需于酒食，贞吉',
      '入于穴，有不速之客三人来',
    ],
  },
  {
    id: 8,
    name: '水地比',
    symbol: '☵☷',
    binarySymbol: '010000',
    upper: '坎',
    lower: '坤',
    palace: '坤',
    description: '吉，原筮，元永贞，无咎',
    yaoCi: [
      '有孚比之，无咎',
      '比之自内，贞吉',
      '比之匪人',
      '外比之，贞吉',
      '显比，王用三驱',
      '比之无首，凶',
    ],
  },

  /* 兑宫 */
  {
    id: 58,
    name: '兑为泽',
    symbol: '☱☱',
    binarySymbol: '110110',
    upper: '兑',
    lower: '兑',
    palace: '兑',
    description: '亨，利贞',
    yaoCi: [
      '和兑，吉',
      '孚兑，吉，悔亡',
      '来兑，凶',
      '商兑，未宁，介疾有喜',
      '孚于剥，有厉',
      '引兑',
    ],
  },
  {
    id: 47,
    name: '泽水困',
    symbol: '☱☵',
    binarySymbol: '110010',
    upper: '兑',
    lower: '坎',
    palace: '兑',
    description: '亨，贞，大人吉',
  },
  {
    id: 45,
    name: '泽地萃',
    symbol: '☱☷',
    binarySymbol: '110000',
    upper: '兑',
    lower: '坤',
    palace: '兑',
    description: '亨，王假有庙',
  },
  {
    id: 31,
    name: '泽山咸',
    symbol: '☱☶',
    binarySymbol: '110100',
    upper: '兑',
    lower: '艮',
    palace: '兑',
    description: '亨，利贞，取女吉',
  },
  {
    id: 39,
    name: '水山蹇',
    symbol: '☵☶',
    binarySymbol: '010100',
    upper: '坎',
    lower: '艮',
    palace: '兑',
    description: '利西南，不利东北',
  },
  {
    id: 15,
    name: '地山谦',
    symbol: '☷☶',
    binarySymbol: '000100',
    upper: '坤',
    lower: '艮',
    palace: '兑',
    description: '亨，君子有终',
    yaoCi: [
      '谦谦君子，用涉大川，吉',
      '鸣谦，贞吉',
      '劳谦，君子有终，吉',
      '无不利，撝谦',
      '不富以其邻，利用侵伐',
      '鸣谦，利用行师',
    ],
  },
  {
    id: 62,
    name: '雷山小过',
    symbol: '☳☶',
    binarySymbol: '001100',
    upper: '震',
    lower: '艮',
    palace: '兑',
    description: '亨，利贞，可小事',
  },
  {
    id: 54,
    name: '雷泽归妹',
    symbol: '☳☱',
    binarySymbol: '001110',
    upper: '震',
    lower: '兑',
    palace: '兑',
    description: '征凶，无攸利',
  },
];

// 导出卦象数据
export const hexagramsData: HexagramData[] = rawHexagramsData;
